-- CREATE NODEA DATABASE FOR MariaDB

DROP DATABASE IF EXISTS nodea;
CREATE DATABASE nodea
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

CREATE USER IF NOT EXISTS 'np_a_msm'@'localhost' IDENTIFIED BY 'np_a_msm';

CREATE USER IF NOT EXISTS 'nodea'@'localhost' IDENTIFIED BY 'N0d3@_S0ftw@re';
CREATE USER IF NOT EXISTS 'nodea'@'127.0.0.1' IDENTIFIED BY 'N0d3@_S0ftw@re';
CREATE USER IF NOT EXISTS 'nodea'@'%' IDENTIFIED BY 'N0d3@_S0ftw@re';
GRANT ALL PRIVILEGES ON *.* TO 'nodea'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'nodea'@'127.0.0.1' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'nodea'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

use nodea;
CREATE TABLE IF NOT EXISTS `sessions` (
  `session_id` varchar(128) COLLATE utf8mb4_bin NOT NULL,
  `expires` int(11) unsigned NOT NULL,
  `data` mediumtext COLLATE utf8mb4_bin,
  PRIMARY KEY (`session_id`)
) ENGINE=InnoDB